// lib/schools.ts
// AUTO-GENERATED from California_Planning.xlsx (Brooke, May 2026).
// 39 schools across 4 tiers. Source of truth for the school dataset.
// Do not hand-edit individual records here; regenerate from the spreadsheet.

export interface SchoolContact {
  role: string;
  name: string;
}

export interface School {
  id: string;
  name: string;
  tier: string;
  location: string;
  enrollment: string;
  projectActivity: string;
  contacts: SchoolContact[];
  /** Historical order/territory notes from the planning sheet — shown to reps when prepping for a visit. */
  notes: string;
}

export const SCHOOL_TIERS = [
  "Tier 1 Private Schools – Strong Music & Athletics",
  "Core Independent / College Prep",
  "Catholic / Faith-Based",
  "Expanded Independent + Regional Private Schools",
] as const;

export const schools: School[] = [
  {
    id: "brentwood-school-east-campus-6-12",
    name: "Brentwood School-East Campus 6-12",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "100 S Barrington Pl., West Los Angeles",
    enrollment: "~1,200",
    projectActivity: "Long-term master plan: Phased expansion through 2040",
    contacts: [
      { role: "Performing Arts Chair", name: "Lauren Hall" },
      { role: "Choral/Orchestra", name: "Charlie Kim" },
      { role: "Football Coach", name: "Jake Ford" },
      { role: "Athletic Director", name: "Dana Vasquez" },
    ],
    notes: "July-Sept 2025, Jan 2026 - no potential",
  },
  {
    id: "flintridge-preparatory-school",
    name: "Flintridge Preparatory School",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "4543 Crown Ave La Cañada Flintridge, CA",
    enrollment: "~530",
    projectActivity: "Continuous upgrades: STEAM building + campus renovations",
    contacts: [
      { role: "Performing Arts Chair", name: "Molli Mattei" },
      { role: "Football Coach", name: "Russell white (also asst AD)" },
      { role: "Athletic Director", name: "Sean Beattie" },
    ],
    notes: "2021 - Auditorium Expansion - no potential\n2024 - StageTek Audience Seating - no potential",
  },
  {
    id: "sierra-canyon-school",
    name: "Sierra Canyon School",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "20801 Rinaldi St. Chatsworth, CA",
    enrollment: "~1,100",
    projectActivity: "Recent + ongoing: arts center + athletics expansion",
    contacts: [
      { role: "Director of Performing Arts", name: "Chris Sampson" },
      { role: "AD/Head Football", name: "Jon Ellinghouse" },
      { role: "Associate Head AD", name: "Katie Fox" },
    ],
    notes: "2022 - flipFORMS",
  },
  {
    id: "crossroads-school",
    name: "Crossroads School",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "1714 21st St., Santa Monica",
    enrollment: "~1,200",
    projectActivity: "Active construction: 55,000 SF Performing Arts Center (~2026)",
    contacts: [],
    notes: "Tam is working on this with architect. She should visit.\n\nWorking with Project Architect, Shuba Krishnaswamy (SPF Architects) on Music Furnishings. https://www.spfa.com/work/crossroads-main-stage-auditorium-building",
  },
  {
    id: "windward-school",
    name: "Windward School",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "11350 Palms Blvd. West Los Angeles",
    enrollment: "~625",
    projectActivity: "Master plan: campus rebuild + performing arts expansion",
    contacts: [
      { role: "Director of Athletics", name: "Tyrone Powell" },
      { role: "Assistant AD", name: "Billy Clemens" },
      { role: "Assistant AD", name: "Jocelyn Castillo" },
      { role: "Director of Vocal and Instrumental Music", name: "Daniel Koh" },
      { role: "Associate Director of Performing Arts", name: "Lisa Weinstein" },
      { role: "Director of Theatre and Dance", name: "Jordan Fox" },
    ],
    notes: "2023 - Jeff Kirkpatrick working with Turner Construction",
  },
  {
    id: "campbell-hall-school",
    name: "Campbell Hall School",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "4533 Laurel Canyon Blvd. Studio City / North Hollywood",
    enrollment: "~1,100",
    projectActivity: "No major recent projects identified",
    contacts: [
      { role: "Athletic Coordinator", name: "Lleyton Wicks" },
      { role: "Director of Athletic Operations", name: "Juan Velazquez, Jr." },
      { role: "Performing Arts Director", name: "Megan Zakarian Adell" },
      { role: "High School Performing Arts", name: "Josh Adell" },
      { role: "High School Performing Arts, Chapel Band, Choir", name: "Jeff Bonhiver" },
    ],
    notes: "2023 - Classic 50 stands",
  },
  {
    id: "viewpoint-school",
    name: "Viewpoint School",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "23620 Mulholland Hwy. Calabasas",
    enrollment: "~1,200",
    projectActivity: "No major current projects identified",
    contacts: [
      { role: "Athletic Director", name: "Josh Frechette" },
      { role: "Instrumental Music", name: "Nick Alvarez, Kimberly Gonzalez, Marisa Mcleod" },
    ],
    notes: "2025 - Student chairs, carts, decks, podium purchase",
  },
  {
    id: "the-webb-schools",
    name: "The Webb Schools",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "1175 W Base Line Rd. Claremont",
    enrollment: "~405",
    projectActivity: "No major active expansion noted",
    contacts: [
      { role: "Fine Arts Department Chair", name: "Stefanie Plumley" },
      { role: "Director of Instrumental Music", name: "Luc Dubreuil" },
      { role: "Associate Director of Athletics", name: "Danielle Wilson" },
    ],
    notes: "This is Jeremy DuBoi's territory (909 territory)",
  },
  {
    id: "oaks-christian-school",
    name: "Oaks Christian School",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "31749 La Tienda Dr., Westlake Village",
    enrollment: "~1,500 (est.)",
    projectActivity: "Active expansion: New TK–3 campus opening 2026",
    contacts: [
      { role: "Head of Athletics", name: "Brad Cook" },
      { role: "AD for Facilites", name: "Paul Black" },
      { role: "Asst to Head of Athletics", name: "Mary Zarraonandia" },
      { role: "Band Director", name: "Vince Trombetta" },
      { role: "Fine Arts Teachers", name: "Eddie Grey, Joe Diblasi, Alicia Langness" },
    ],
    notes: "2026 - SoundLok Gasketing",
  },
  {
    id: "marymount-high-school",
    name: "Marymount High School",
    tier: "Tier 1 Private Schools – Strong Music & Athletics",
    location: "10643 Sunset Blvd., Los Angeles",
    enrollment: "~310",
    projectActivity: "Facility upgrades: science labs + arts renovations",
    contacts: [
      { role: "Director of Athletics", name: "Meghan Cadenas" },
      { role: "Assistant Director of Athletics", name: "Jemila Brady" },
      { role: "Choral Director", name: "Kendall Renaud" },
      { role: "Director of Finance & Operations", name: "Lori Paillet" },
    ],
    notes: "2019 - Last Order 2014, Folio Cabinet",
  },
  {
    id: "westridge-school",
    name: "Westridge School",
    tier: "Core Independent / College Prep",
    location: "324 Madeline Dr. Pasadena, CA",
    enrollment: "~550",
    projectActivity: "Ongoing campus improvements: multi-phase expansion incl. science center + campus growth plan",
    contacts: [
      { role: "Director of Athletics", name: "Alice Lee" },
      { role: "Assistant Director of Athletics", name: "Jenna Wong" },
      { role: "Director of Theatre", name: "Brandon Kruhm" },
      { role: "Choir Director", name: "Shinnshill Park" },
      { role: "Music", name: "Rachel Counihan" },
    ],
    notes: "2025 - Tourmaster additions, replacement parts",
  },
  {
    id: "archer-school-for-girls",
    name: "Archer School for Girls",
    tier: "Core Independent / College Prep",
    location: "11725 Sunset Blvd, Brentwood (Los Angeles, CA)",
    enrollment: "~500",
    projectActivity: "Major master plan: “Archer Forward” (academic, athletics, arts expansion)",
    contacts: [
      { role: "Finance & Operations", name: "Jane Davis" },
      { role: "Arts Department Chair", name: "Joe Schenck" },
      { role: "Director of Athletics", name: "Kim Smith" },
    ],
    notes: "1999-2018 - Total sales $8K",
  },
  {
    id: "oakwood-school",
    name: "Oakwood School",
    tier: "Core Independent / College Prep",
    location: "11600 Magnolia Blvd (Secondary) / 11230 Moorpark St (Elementary) North Hollywood / Studio City, CA",
    enrollment: "~800 (est.)",
    projectActivity: "Incremental upgrades: phased campus improvements",
    contacts: [
      { role: "Athletic Director", name: "Kort Jensen, Steve Smith" },
      { role: "Chief Operating Officer", name: "Christopher Thomas" },
    ],
    notes: "2022 (Secondary) - Classic 50 Stands\n2013 (Elementary) - flipFORMS",
  },
  {
    id: "wildwood-school",
    name: "Wildwood School",
    tier: "Core Independent / College Prep",
    location: "11811 Olympic Blvd (Secondary)/ 12201 Washington Pl (Elementary) West Los Angeles, CA",
    enrollment: "~700",
    projectActivity: "Recently modernized campus: no major active construction",
    contacts: [
      { role: "Music Teachers", name: "Itai Disraeli, Paula Gabriel, Hagai Izraeli" },
      { role: "Theatre Teacher", name: "Seth Gordon" },
      { role: "Athletic Director", name: "Billy DuMone" },
      { role: "Assistant Athletic Director", name: "Reo Sorrentino" },
    ],
    notes: "2021 (Secondary) - no orders, quote for stand & move cart\n2007 (Elementary) - music stands, lights, tall folio cabinets",
  },
  {
    id: "new-roads-school",
    name: "New Roads School",
    tier: "Core Independent / College Prep",
    location: "3131 Olympic Blvd. Santa Monica, CA",
    enrollment: "~550",
    projectActivity: "Stable campus: no major current build; prior improvements completed",
    contacts: [
      { role: "Director of Athletics", name: "Richard Jenkins" },
      { role: "Director of Music", name: "Stephen Billington" },
    ],
    notes: "2023 - Theatre inspection (there are three separate schools under this umbrella)",
  },
  {
    id: "pilgrim-school",
    name: "Pilgrim School",
    tier: "Core Independent / College Prep",
    location: "540 S Commonwealth Ave, Los Angeles, CA",
    enrollment: "~328",
    projectActivity: "No major capital projects identified: program-focused investment",
    contacts: [
      { role: "Arts Department Chair & Elementary Music", name: "Bryanna Miller" },
      { role: "Music Teacher", name: "Tyler Stein" },
      { role: "Athletic Director", name: "Sam Taub" },
    ],
    notes: "1994 - footnotes rug",
  },
  {
    id: "rolling-hills-prep",
    name: "Rolling Hills Prep",
    tier: "Core Independent / College Prep",
    location: "1 Rolling Hills Prep Way San Pedro, CA",
    enrollment: "~225",
    projectActivity: "No major construction: stable campus footprint",
    contacts: [
      { role: "Music Teacher & Visual/Performing Arts Chair", name: "Tanner Pfeiffer" },
      { role: "Athletic Coordinator", name: "Lance Hollandsworth" },
    ],
    notes: "2019 - drape quote",
  },
  {
    id: "sequoyah-school",
    name: "Sequoyah School",
    tier: "Core Independent / College Prep",
    location: "K-8 Campus: 535 S Pasadena Ave\nHigh School Campus: 301 N Orange Grove Blvd\nAdministration: 500 S Pasadena Avenue",
    enrollment: "~350 (est.)",
    projectActivity: "Limited visibility: no significant current projects identified",
    contacts: [
      { role: "Music", name: "Ben Ede" },
      { role: "Theater&Performing Arts Chair", name: "Arden Thomas" },
      { role: "Director of Athletics", name: "Brian Knigin" },
    ],
    notes: "no activity or quotes",
  },
  {
    id: "st-john-bosco-hs",
    name: "St. John Bosco HS",
    tier: "Catholic / Faith-Based",
    location: "13640 Bellflower Blvd Bellflower, CA",
    enrollment: "~1,000 (est.)",
    projectActivity: "Ongoing strategic upgrades: long-term campus modernization",
    contacts: [
      { role: "Music Director/Visual & Performing Arts", name: "Ramon Villanueva, Jr." },
      { role: "Director of Theatre", name: "Martin Lang" },
      { role: "Director of Athletics", name: "Vince Brown" },
      { role: "Associate Athletic Director", name: "Jon Hall" },
      { role: "Football Coach", name: "Jason Negro" },
      { role: "Activities Director", name: "Donminic Ellison" },
    ],
    notes: "2009 - mobile kiosk",
  },
  {
    id: "notre-dame-hs-sherman-oaks",
    name: "Notre Dame HS (Sherman Oaks)",
    tier: "Catholic / Faith-Based",
    location: "13645 Riverside Dr Sherman Oaks, CA",
    enrollment: "~1,200",
    projectActivity: "Active expansion: athletics, aquatics, parking; future dining commons",
    contacts: [
      { role: "Performing Arts Chair", name: "Amanda Tepe" },
      { role: "Choir", name: "David Conley" },
      { role: "Band Directors", name: "Matthew Pagnotta, Lilian Diaz" },
      { role: "Theatre Director", name: "Chris Wollman" },
      { role: "Director of Athletics", name: "Alec Moss" },
      { role: "Athletics Coordinator", name: "Jena Laolagi" },
      { role: "Assistant Athletics", name: "Gregory Moss" },
    ],
    notes: "2018 - preface conductor's stand",
  },
  {
    id: "bishop-montgomery-hs",
    name: "Bishop Montgomery HS",
    tier: "Catholic / Faith-Based",
    location: "5430 Torrance Blvd Torrance, CA",
    enrollment: "~850–900",
    projectActivity: "Recent investment: STEAM labs + athletics upgrades",
    contacts: [
      { role: "Music Director", name: "Jacob White" },
      { role: "Visual & Performing Arts Chair", name: "Jennifer Kallok" },
      { role: "Interim Athletic Director", name: "Rheina Ale" },
      { role: "Assistant Athletic Director", name: "Oscar McBride" },
    ],
    notes: "1998- chairs & tablet arms",
  },
  {
    id: "alemany-hs",
    name: "Alemany HS",
    tier: "Catholic / Faith-Based",
    location: "11111 N Alemany Dr Mission Hills, CA",
    enrollment: "~1,300 (est.)",
    projectActivity: "Incremental upgrades: ongoing campus improvements",
    contacts: [
      { role: "Music/Band Director", name: "Lindsey Colella" },
      { role: "Visual & Performing Arts Chair", name: "Charlotte Mullich" },
      { role: "Theatre Director", name: "Virginia Alkazian" },
      { role: "Athletic Director", name: "Randy Thompson" },
      { role: "Football Coach", name: "Dennis Keyes" },
    ],
    notes: "2007 - x carts",
  },
  {
    id: "chaminade-college-prep",
    name: "Chaminade College Prep",
    tier: "Catholic / Faith-Based",
    location: "7500 Chaminade Ave West Hills, CA",
    enrollment: "~1,360",
    projectActivity: "Major expansion underway: classroom building, athletics, aquatic center",
    contacts: [
      { role: "Athletic Director", name: "Todd Borowski" },
      { role: "Football Coach", name: "David Machuca" },
      { role: "Fine Arts Department Chair", name: "Yvette Bishop" },
    ],
    notes: "2024 - signature risers",
  },
  {
    id: "louisville-hs",
    name: "Louisville HS",
    tier: "Catholic / Faith-Based",
    location: "22300 Mulholland Dr Woodland Hills, CA",
    enrollment: "~290",
    projectActivity: "Recent upgrades: innovation lab + campus improvements",
    contacts: [
      { role: "Athletic Director", name: "Marilyn Hyman" },
      { role: "Assistant Athletic Director", name: "Ariana Martinez" },
      { role: "Performing Arts Department Chair", name: "Tracy Powell" },
      { role: "Performing Arts Faculty", name: "Dan Mailley, Connor Smith" },
    ],
    notes: "1989 - choral folios",
  },
  {
    id: "fairmont-prep",
    name: "Fairmont Prep",
    tier: "Catholic / Faith-Based",
    location: "2200 W Sequoia Ave Anaheim, CA",
    enrollment: "~650",
    projectActivity: "Stable campus: no major current build",
    contacts: [
      { role: "Athletic Director", name: "Alexis Price" },
      { role: "Assistant Athletic Director", name: "Shane Beatty" },
      { role: "Visual/Performing Arts Chair", name: "Nick Ochoa" },
      { role: "Music/Theatre", name: "Ashley Song" },
    ],
    notes: "Jeremy DuBois's territory - 2011 signature risers",
  },
  {
    id: "cathedral-high-school",
    name: "Cathedral High School",
    tier: "Catholic / Faith-Based",
    location: "1253 Bishops Rd Los Angeles, CA",
    enrollment: "~800 (est.)",
    projectActivity: "Major project completed: performing arts complex",
    contacts: [
      { role: "Visual/Performing Arts Staff", name: "Megan DeBoard, Roch Dufresne, Noah Lopez, Jamie Murphy" },
      { role: "Athletic Director", name: "Janae Hylland" },
    ],
    notes: "2005 - percussion cabinet\n**Last day of School on May 28th.",
  },
  {
    id: "mayfield-senior-school",
    name: "Mayfield Senior School",
    tier: "Catholic / Faith-Based",
    location: "500 Bellefontaine St. Pasadena, CA",
    enrollment: "~330",
    projectActivity: "Campus improvements: master plan + renovations",
    contacts: [
      { role: "Director of Athletics", name: "Steve Bergen" },
      { role: "Assistant AD", name: "Lydia Arguelles" },
      { role: "Director of Facilities", name: "Bill Lewis" },
      { role: "Instrumental Teacher", name: "Christin Hablewitz" },
      { role: "Choir Director", name: "Andrew Alvarez" },
    ],
    notes: "2003 - Legacy Shell",
  },
  {
    id: "st-francis-hs",
    name: "St. Francis HS",
    tier: "Catholic / Faith-Based",
    location: "200 Foothill Blvd La Cañada Flintridge, CA",
    enrollment: "~900 (est.)",
    projectActivity: "Ongoing reinvestment: no major current project",
    contacts: [
      { role: "Director of Theater Arts", name: "Emmanuel Eulalia" },
      { role: "Theater Arts Instructor", name: "Claire Jacobs" },
      { role: "Director of Athletics", name: "Matthew Luderer" },
      { role: "Assistant AD", name: "Edward Corcoran" },
    ],
    notes: "2011 - percussion workstation\n*Doesn't seem to have a music program, just theater",
  },
  {
    id: "la-salle-college-prep",
    name: "La Salle College Prep",
    tier: "Catholic / Faith-Based",
    location: "3880 E Sierra Madre Blvd Pasadena, CA",
    enrollment: "~600",
    projectActivity: "Long-term master plan: athletics, arts, classroom expansion",
    contacts: [
      { role: "Director of Instrumental Music", name: "Greg Ziomek" },
      { role: "Performing Arts Instructor", name: "Brian Drummy" },
      { role: "Athletic Director", name: "Daniel Threadgill" },
    ],
    notes: "2015 - stagetek",
  },
  {
    id: "providence-high-school",
    name: "Providence High School",
    tier: "Expanded Independent + Regional Private Schools",
    location: "511 S Buena Vista St. Burbank, CA",
    enrollment: "~400 (est.)",
    projectActivity: "No major capital projects identified: stable campus environment",
    contacts: [
      { role: "Dean of Arts", name: "Julianne Kusmierczyk" },
      { role: "Choir Director", name: "Marisa Bradfield" },
      { role: "Theatre Operations", name: "Annie Terry" },
      { role: "Athletic Director", name: "James Jimenez" },
      { role: "Assistant Athletic Director", name: "Le'Von Davis" },
    ],
    notes: "2019 - Nota chairs, flex system",
  },
  {
    id: "ef-academy-pasadena",
    name: "EF Academy Pasadena",
    tier: "Expanded Independent + Regional Private Schools",
    location: "1539 E Howard St. Pasadena, CA",
    enrollment: "~300 (est.)",
    projectActivity: "Newer purpose-built campus: modern facilities with recent development",
    contacts: [
      { role: "Music", name: "Sydney Moss" },
      { role: "Athletic Director", name: "Justin Clapp" },
    ],
    notes: "no activity or quotes",
  },
  {
    id: "southwestern-academy",
    name: "Southwestern Academy",
    tier: "Expanded Independent + Regional Private Schools",
    location: "2800 Monterey Rd San Marino, CA",
    enrollment: "~200 (est.)",
    projectActivity: "No major construction activity: stable campus footprint",
    contacts: [
      { role: "Athletic Director and Drama", name: "Thomas Bornt" },
      { role: "Director of Operations", name: "Peter Casarez" },
      { role: "Visual/Performing Arts Chair", name: "John Kohn" },
    ],
    notes: "1998 - Travelmaster, class piano workstation",
  },
  {
    id: "the-thacher-school",
    name: "The Thacher School",
    tier: "Expanded Independent + Regional Private Schools",
    location: "5025 Thacher Rd Ojai, CA",
    enrollment: "~260 (est.)",
    projectActivity: "Ongoing campus upgrades: typical boarding school reinvestment",
    contacts: [
      { role: "Director of Music Program", name: "Gregory Haggard" },
      { role: "Director of Instrumental Music", name: "Evan Avery" },
      { role: "Director of Theater", name: "Grace Lowe" },
      { role: "Athletic Director", name: "Etienne Emanuel" },
    ],
    notes: "2023 - student chairs",
  },
  {
    id: "idyllwild-arts-academy",
    name: "Idyllwild Arts Academy",
    tier: "Expanded Independent + Regional Private Schools",
    location: "52500 Temecula Rd Idyllwild, CA",
    enrollment: "~300 (est.)",
    projectActivity: "Continuous arts investment: studios + performance facilities",
    contacts: [
      { role: "Head of School/Music Faculty", name: "Jason Hallowbard" },
      { role: "Music Chair", name: "Kai Potts Smith" },
      { role: "Dramatic Arts Chair", name: "Denis McCourt Stryjewski" },
      { role: "Musical Theater/Music Director", name: "Jeff Bell" },
      { role: "Business Operations", name: "Christina Steinbacher" },
    ],
    notes: "Jeremy DuBois' territory - 2019 chairs and carts\n*Specific arts school",
  },
  {
    id: "echo-horizon-school",
    name: "Echo Horizon School",
    tier: "Expanded Independent + Regional Private Schools",
    location: "3430 McManus Ave Culver City, CA",
    enrollment: "~300 (est.)",
    projectActivity: "Recently modernized campus: no major active expansion",
    contacts: [
      { role: "Music/Choir", name: "Elizabeth Cohn" },
    ],
    notes: "no activity \n*Grades 4-6",
  },
  {
    id: "turning-point-school",
    name: "Turning Point School",
    tier: "Expanded Independent + Regional Private Schools",
    location: "14618 Sylvan St Culver City, CA",
    enrollment: "~300 (est.)",
    projectActivity: "No major public projects identified: incremental improvements only",
    contacts: [
      { role: "Director of Athletics", name: "Jacob Synder" },
      { role: "Music Teacher (Grade 3-8)", name: "Lilly Aycud" },
      { role: "Music Teacher (PreK-2)", name: "Gianluca Bersanetti" },
      { role: "Theater Coordinator", name: "Josh Lesser" },
    ],
    notes: "2020 - taxi carts\n* PreK-8 school",
  },
  {
    id: "le-lyc-e-fran-ais-de-la",
    name: "Le Lycée Français de LA",
    tier: "Expanded Independent + Regional Private Schools",
    location: "3261 Overland Ave (main campus) Los Angeles, CA",
    enrollment: "~1,000+ (est.)",
    projectActivity: "Distributed campuses: periodic upgrades across locations",
    contacts: [
      { role: "Athletic Director", name: "Greg Power" },
    ],
    notes: "no activity \n*No name listed for the arts but they do show that they have music, dance, theater on their website.",
  },
  {
    id: "immaculate-heart-hs",
    name: "Immaculate Heart HS",
    tier: "Expanded Independent + Regional Private Schools",
    location: "5515 Franklin Ave Los Angeles, CA",
    enrollment: "~700 (est.)",
    projectActivity: "No major active construction identified: steady reinvestment",
    contacts: [
      { role: "Choir Director", name: "Greg Koppenhaver" },
      { role: "Athletic Director", name: "Kevin Cadenas" },
      { role: "Fine Arts Teachers", name: "Al Grindon, Heather Chesley, Lucinda Hanshaw" },
    ],
    notes: "1993 - risers",
  },
  {
    id: "berkeley-hall-school",
    name: "Berkeley Hall School",
    tier: "Expanded Independent + Regional Private Schools",
    location: "15700 Mulholland Dr Los Angeles, CA",
    enrollment: "~300 (est.)",
    projectActivity: "Campus modernization completed: no major new projects active",
    contacts: [
      { role: "Music Teacher", name: "Geoffrey Fontaine" },
      { role: "Theater Teacher", name: "Madi Lang-Ree" },
      { role: "Athletic Director", name: "Justin Myers" },
    ],
    notes: "2009 - versalite decks\n**Grades PreK-8",
  },
];

export default schools;
